
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package app;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OP_MAY_IG = 42;
  public static final int PROGRAM_BEGIN = 32;
  public static final int BLOCK_END = 12;
  public static final int INTEGER = 24;
  public static final int OP_NOT = 39;
  public static final int OP_AND = 37;
  public static final int DOS_PUNTOS = 18;
  public static final int CONST_DOU = 21;
  public static final int OP_ASIGN = 2;
  public static final int WRITE = 19;
  public static final int OP_DIV = 5;
  public static final int MIDDLE = 34;
  public static final int DEFINE = 30;
  public static final int DEFINE_END = 31;
  public static final int BLOCK_BEG = 11;
  public static final int BRACK_OPEN = 13;
  public static final int IF = 28;
  public static final int OP_MEN_IG = 43;
  public static final int ID = 35;
  public static final int PUNTO_COMA = 15;
  public static final int OP_MOD = 7;
  public static final int EOF = 0;
  public static final int CONST_BIN = 22;
  public static final int error = 1;
  public static final int COMA = 16;
  public static final int OP_MULT = 6;
  public static final int OP_OR = 38;
  public static final int OP_RESTA = 4;
  public static final int OP_MEN = 40;
  public static final int OP_IG = 44;
  public static final int PROGRAM_END = 33;
  public static final int ELSE = 29;
  public static final int PUNTO = 17;
  public static final int WHILE = 27;
  public static final int FLOAT = 26;
  public static final int OP_MAY = 41;
  public static final int STRING = 25;
  public static final int CONST_STR = 36;
  public static final int OP_SUMA = 3;
  public static final int PAREN_CLOSE = 10;
  public static final int BRACK_CLOSE = 14;
  public static final int OP_POT = 8;
  public static final int OP_DIST = 45;
  public static final int CONST_INT = 20;
  public static final int PAREN_OPEN = 9;
  public static final int CONST_HEX = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OP_ASIGN",
  "OP_SUMA",
  "OP_RESTA",
  "OP_DIV",
  "OP_MULT",
  "OP_MOD",
  "OP_POT",
  "PAREN_OPEN",
  "PAREN_CLOSE",
  "BLOCK_BEG",
  "BLOCK_END",
  "BRACK_OPEN",
  "BRACK_CLOSE",
  "PUNTO_COMA",
  "COMA",
  "PUNTO",
  "DOS_PUNTOS",
  "WRITE",
  "CONST_INT",
  "CONST_DOU",
  "CONST_BIN",
  "CONST_HEX",
  "INTEGER",
  "STRING",
  "FLOAT",
  "WHILE",
  "IF",
  "ELSE",
  "DEFINE",
  "DEFINE_END",
  "PROGRAM_BEGIN",
  "PROGRAM_END",
  "MIDDLE",
  "ID",
  "CONST_STR",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "OP_MEN",
  "OP_MAY",
  "OP_MAY_IG",
  "OP_MEN_IG",
  "OP_IG",
  "OP_DIST"
  };
}

